name:                hstrie
version:             0.1.0.0
github:              "oisdk/hstrie"
license:             MIT
author:              "Donnacha Oisín Kidney"
maintainer:          "mail@doisinkidney.com"
copyright:           "2018 Donnacha Oisín Kidney"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/oisdk/hstrie#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- lens
- these
- profunctors
- vector
- deepseq

default-extensions:
- TypeOperators
- StandaloneDeriving
- MultiParamTypeClasses
- FlexibleContexts
- FlexibleInstances
- GADTs
- TypeFamilies
- TypeFamilyDependencies
- FunctionalDependencies
- RankNTypes
- UnicodeSyntax
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- ConstraintKinds
- ScopedTypeVariables
- KindSignatures
- DataKinds
- BangPatterns

library:
  source-dirs: src

ghc-options:
- -Wall
- -fwarn-incomplete-record-updates
- -fwarn-incomplete-uni-patterns
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
    - -fwarn-redundant-constraints
    - -Wcompat

tests:
  hstrie-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hstrie
    - hedgehog
    - hedgehog-checkers
    - hedgehog-checkers-lens
  hstrie-doctests:
    main:                doctests.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    dependencies:
    - hstrie
    - doctest
    - QuickCheck

benchmarks:
  bench:
    main: bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - hstrie
    - criterion
    - random
